trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- bash: |
    curl -k -O -u sean:foobar $TL_CONSOLE/api/v1/util/twistcli
    chmod a+x twistcli
    ./twistcli images scan --address $TL_CONSOLE -u sean -p foobar --details $(imageName):$(Build.BuildId)