trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  containerRegistry: 'twistlocktest.azurecr.io'
  dockerRegistryServiceConnection: 'e3d40d8b-fc1b-4a97-9824-90dffd80ad0c'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: testimage
    command: build
    containerRegistry: $(dockerRegistryServiceConnection)
    Dockerfile: app/Dockerfile
- task: Bash@3
  displayName: Twistcli Scan
  inputs:
    targetType: inline
    script: 
      curl -k -O -u $USER:$PW $TL_CONSOLE/api/v1/util/twistcli;
      chmod a+x twistcli;
      ./twistcli images scan --address $TL_CONSOLE -u $USER -p $PW --details $(containerRegistry)/testimage:$(Build.BuildId);
#- task: Docker@2
#  displayName: Push to registry
#  inputs: 
#    command: push
#    containerRegistry: $(dockerRegistryServiceConnection)
#    repository: testimage